# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shoris < Formula
  desc ""
  homepage "https://github.com/borischen0203/homebrew-shoris"
  version "0.2.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/borischen0203/shoris/releases/download/v0.2.2/shoris_0.2.2_Darwin_arm64.tar.gz"
      sha256 "d972b3d2517911398eeb1be143fb88804f52195c2469dff38a6527aa5242b3a0"

      def install
        bin.install "shoris"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/borischen0203/shoris/releases/download/v0.2.2/shoris_0.2.2_Darwin_x86_64.tar.gz"
      sha256 "df9ae0e2d97b34d19019f0a7b08951149787ad3b00d71fa1dee1f06f5194c664"

      def install
        bin.install "shoris"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/borischen0203/shoris/releases/download/v0.2.2/shoris_0.2.2_Linux_x86_64.tar.gz"
      sha256 "9718dffbe9efaf83961b3631a241196cf5cbd8f0803ec35533862d5d41f987ff"

      def install
        bin.install "shoris"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/borischen0203/shoris/releases/download/v0.2.2/shoris_0.2.2_Linux_arm64.tar.gz"
      sha256 "7b113f6cd92c3a4bdf6b06e787a1da78ef65e2387a2a615c7b433a7ea1dcfd82"

      def install
        bin.install "shoris"
      end
    end
  end
end
