# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shoris < Formula
  desc ""
  homepage "https://github.com/borischen0203/homebrew-shoris"
  version "0.1.9"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/borischen0203/shoris/releases/download/v0.1.9/shoris_0.1.9_Darwin_x86_64.tar.gz"
      sha256 "0e1bd97d8a32fedbaa3c12f71967507b53098c51a072eed96afb241485c3c7d8"

      def install
        bin.install "shoris"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/borischen0203/shoris/releases/download/v0.1.9/shoris_0.1.9_Darwin_arm64.tar.gz"
      sha256 "813ee4e5ada9b1b614a4cbf65ec7687eff7c223d77317889ca3b7ae922421636"

      def install
        bin.install "shoris"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/borischen0203/shoris/releases/download/v0.1.9/shoris_0.1.9_Linux_x86_64.tar.gz"
      sha256 "f3cccbe5d72f97ddee2f0b46cedbe80c3c6646d09eef0b68dee5211340a3eae3"

      def install
        bin.install "shoris"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/borischen0203/shoris/releases/download/v0.1.9/shoris_0.1.9_Linux_arm64.tar.gz"
      sha256 "2fb24ed752f2b816d6077f21520ed8ae810bb740716dd1b3aebfedf4cc515a49"

      def install
        bin.install "shoris"
      end
    end
  end
end
